//定义消息名称
export const REGISTER_USER_INFO = 'REGISTER_USER_INFO';
export const LOGIN_USER_INFO = 'LOGIN_USER_INFO';
export const CHECK_SESSION = 'CHECK_SESSION';
export const CLICK_PERSONAL_INFO = 'CLICK_PERSONAL_INFO';